/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#ffb787",
        "surface-container-high": "#ede6f1",
        "tertiary": "#006495",
        "surface": "#fef7ff",
        "surface-container-highest": "#e7e0ec",
        "on-primary-container": "#5e2b00",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#322f38",
        "secondary": "#615c66",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "outline-variant": "#dfc1af",
        "on-background": "#1d1a22",
        "on-secondary-fixed": "#1d1a22",
        "on-error-container": "#93000a",
        "surface-container": "#f3ebf7",
        "outline": "#8b7263",
        "on-tertiary-fixed": "#001e30",
        "primary": "#964900",
        "on-surface": "#1d1a22",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#cbc4cf",
        "tertiary-fixed-dim": "#90cdff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#311300",
        "secondary-container": "#e7e0ec",
        "inverse-on-surface": "#f6eefa",
        "tertiary-container": "#00acfd",
        "on-error": "#ffffff",
        "inverse-primary": "#ffb787",
        "surface-variant": "#e7e0ec",
        "primary-fixed": "#ffdcc7",
        "secondary-fixed": "#e7e0ec",
        "surface-bright": "#fef7ff",
        "on-secondary-fixed-variant": "#49454e",
        "error": "#ba1a1a",
        "tertiary-fixed": "#cbe6ff",
        "background": "#fef7ff",
        "surface-tint": "#964900",
        "on-primary-fixed-variant": "#723600",
        "on-secondary-container": "#67626c",
        "surface-dim": "#dfd7e3",
        "on-tertiary-fixed-variant": "#004b72",
        "on-tertiary-container": "#003d5d",
        "on-surface-variant": "#574235",
        "surface-container-low": "#f9f1fd",
        "primary-container": "#ff8000"
      },
      fontFamily: {
        "headline": ["Lexend", "sans-serif"],
        "body": ["Lexend", "sans-serif"],
        "label": ["Lexend", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
